#################################
# USER SETTINGS

# 何秒で次に進むか、インターバルの設定
interval: 3600

# 開始の日時指定
# 終わりの日時指定
startday: "2017/8/1 11:00:00"
endday:   "2017/8/1 15:00:00"

# 常にスキップする時間 ２桁の０埋め　分まで。秒は入れない。"01:03"
skiptime:
  - "14:00"
  - "16:00"

# 特殊追加日付
addday:
  - "2017/8/1 9:30:00"
  - "2017/8/1 10:02:00"
  - "2017/8/2 23:00:00"

# interval設定では入らないが必要な時間を列挙

# TODOスキップする特定の日付の特定の時間


# ある時間設定になったあと、常に実行するコマンド
# 実行プログラムの結果を取得して判定するなどの検証プログラムを設定したりする。
post_exec:
  - "wget -P ./result  http://192.168.33.20/limitpage.php "
#  - "cd ~/timetest_src/timetest/testcmd; rspec "


# TODO 2 特定時間設定になったあと、実行するコマンド
# TODO 2 接続サーバー設定
# TODO 2 接続サーバー毎の実行プログラム



# 時間設定時、その時間の前のX秒前にする
time_before_set: 8

# 時間設定後、sleepする時間（cron、atはこの間にバックグラウンドで実行されているはず）
time_sleep_sec: 5

# TODO 2 特定日時でsleepする時間
# TODO 2 対象サーバーOSの抽象化

